default_agent: testeast
agents:
  my_agent:
    name: my_agent
    entrypoint: my_agent.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::983760593521:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-e72c1a7c7a
      execution_role_auto_create: false
      account: '983760593521'
      region: us-east-1
      ecr_repository: 983760593521.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-my_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: my_agent-2C7sGqBCGK
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:983760593521:runtime/my_agent-2C7sGqBCGK
      agent_session_id: 6a71a556-38da-4a3f-b137-f1f490aa3bfc
    codebuild:
      project_name: bedrock-agentcore-my_agent-builder
      execution_role: arn:aws:iam::983760593521:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-e72c1a7c7a
      source_bucket: bedrock-agentcore-codebuild-sources-983760593521-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
  testeast:
    name: testeast
    entrypoint: my_agent.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::983760593521:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-92264d42ec
      execution_role_auto_create: false
      account: '983760593521'
      region: us-east-1
      ecr_repository: 983760593521.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-testeast
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: testeast-XyXgyD558N
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:983760593521:runtime/testeast-XyXgyD558N
      agent_session_id: 3d8d224b-4507-4dc5-8222-58f138e8dd57
    codebuild:
      project_name: bedrock-agentcore-testeast-builder
      execution_role: arn:aws:iam::983760593521:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-92264d42ec
      source_bucket: bedrock-agentcore-codebuild-sources-983760593521-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
